### ISSUE TITLE
Incorrect type conversion when multiplying scalar by Term

### ISSUE THREAD

**Issue by rdeits** [blegat/MultivariatePolynomials.jl#26]
This happened to occur for `JuMP.Variable`, but I suspect it will come up for other types as well:

```julia
using JuMP
m = Model()
@variable m x

using MultivariatePolynomials
@polyvar t

terms = [1, t]

x * terms[1]
```

gives:

```
MethodError: Cannot `convert` an object of type JuMP.Variable to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.

 in *(::JuMP.Variable, ::MultivariatePolynomials.Term{true,Int64}) at /Users/rdeits/.julia/v0.5/MultivariatePolynomials/src/calg.jl:90
```

The offending line is https://github.com/blegat/MultivariatePolynomials.jl/blob/06f2beda153c90bb1d3929dadc1dee05943bae20/src/calg.jl#L90 which tries to convert `x` to type `Int64`.

**Comment by blegat** [comment]
Good catch ! This conversion is indeed useless :-P

**Comment by rdeits** [comment]
Thank you! By the way, have you thought about registering this package? I was hoping to show another lab how easy it is to do polynomial optimization in Julia, and having this package registered would make that a lot easier.

**Comment by blegat** [comment]
Yes, it would be good to register MultivariatePolynomials, PolyJuMP and SumOfSquares. @joehuchette was also willing to get it registered.
@chriscoey @joehuchette @ameliaperry Have you got anything you want to add or be fixed before a first release ?

**Comment by joehuchette** [comment]
I think things are in great shape for an initial release!

**Comment by chriscoey** [comment]
good work!

Pajarito will get a new release soon too - MISDP is improved.
