### ISSUE TITLE
Dynamically create new variables

### ISSUE THREAD

**Issue by saschatimme** [blegat/MultivariatePolynomials.jl#45]
I have code where I need to introduce an additional variable. Currently I just pass this new variable along with the actual polynomial, but that is not really nice.

How would it be if we define a function
```julia
similarvariable(f::MP.AbstractPolynomial, varname::Symbol)::MP.AbstractVariable
```
to be implemented by each implementation?

**Comment by blegat** [comment]
I am not sure to understand what is the issue. What do you mean by "pass this new variable along with the actual polynomial" ?

I can see the issue of being able to create a new variable while being implementation independent. For this, `similarvariable` would be useful.
It would however need to have the signature
```julia
similarvariable(f::MP.AbstractPolynomial, ::Type{Val{V}})::MP.AbstractVariable
```
where `V` is a `Symbol` to be type stable.
Indeed, in TypedPolynomials, the variable have a different type for each symbol.

We could do a macro
```julia
@similarpolyvar p newname
```
to make it easier.

Do you know the symbol at compile time ?

**Comment by saschatimme** [comment]
>I am not sure to understand what is the issue. What do you mean by "pass this new variable along with the actual polynomial" ?

I probably formulated it overly complicated.
Let's say I want to have something like

```julia 
function extend(f)
   @similarpolyvar s
   f * s
end
```

What I do now instead is
```julia 
function extend(f, s)
   f * s
end
```

The macro sounds useful, but I don't think I can guarantee to know the symbol at compile time. There could be cases where I need a dynamic number of new variables. (I ran into a similar issue as I wanted to call `@polyvar x[1:n]` where n was dynamic).

**Comment by blegat** [comment]
We could probably define
```julia
similarvariable(p, ::Type{Val{V}})
similarvariable(p, s::Symbol) = similarvariable(p, Type{s})
```
Calling the first one is preferred since it is type stable for TypedPolynomials but you can still call the second one. It will be type unstable but this effect is negligible in some cases.
`@polyvar[1:n]` is only supported by DynamicPolynomials at the moment but it might be possible to add it to TypedPolynomials even if it is type unstable.
