### ISSUE TITLE
degree and exponent

### ISSUE THREAD

**Issue by blegat** [blegat/MultivariatePolynomials.jl#48]
Currently, julia complains when we export `exponent` because Base already exports
```
exponent(x) -> Int
Get the exponent of a normalized floating-point number.
```
Currently `deg` returns the total degree of a monomial, i.e. the sum of the exponents. If feels a bit odd not to call it `degree` instead since it is the only function for which we have shorten the name.

What do you think of defining:
```julia
degree(m) # -> total degree
degree(m, v) # -> degree of variables v, replaces than exponent(m, v)
```
should we also replace `exponents` by `degrees` ?

**Comment by saschatimme** [comment]
The `degree` change makes total sense for me, but I think we should keep `exponents`. No hard facts but I would personally always talk about the exponents of monomial and not of its degrees.
