### ISSUE TITLE
ETA new version release

### ISSUE THREAD

**Issue by saschatimme** [blegat/MultivariatePolynomials.jl#49]
No rush, just wanted to know when you plan to cut a new release for this package and also for `DynamicPolynomials`, since I have some stuff which relies on this packages :)

**Comment by blegat** [comment]
It will probably be in a week or two once the documentation is done and things have settled down a bit. I am currently implemented a solver for system of polynomial equations in https://github.com/blegat/SemialgebraicSets.jl and I will need to update PolyJuMP.jl and SumOfSquares.jl so I will probably have to change a few things here to make these work.

**Comment by saschatimme** [comment]
Funny, I'm also dabbling around with solving systems of polynomials using homotopy continuation, i.e. the systems have to be square, in https://github.com/saschatimme/HomotopyContinuation.jl. I also made https://github.com/saschatimme/FixedPolySystem.jl which integrate with MultivariatePolynomials for fast evaluation. 
Maybe there's something useful for you.

**Comment by blegat** [comment]
I have created a milestone to keep track of what's left to be done before v0.1.0 : https://github.com/blegat/MultivariatePolynomials.jl/milestone/1

**Comment by blegat** [comment]
It is [happening now](https://github.com/JuliaLang/METADATA.jl/pull/11028)
