### ISSUE TITLE
Polynomials of noncommuting variables

### ISSUE THREAD

**Issue by peterwittek** [blegat/MultivariatePolynomials.jl#7]
Hi,

Do you think the package could be extended with finite effort to work with polynomials of noncommuting operators? I see that [PolyJuMP](https://github.com/JuliaOpt/PolyJuMP.jl) relies on this package to implement the Lasserre hierarchy. We work on a [Python implementation](https://github.com/peterwittek/ncpol2sdpa) of the noncommutative generalization, the [NPA hierarchy](https://arxiv.org/abs/0903.4368). Given the bottlenecks we face, it would make a lot of sense to move development to Julia. Thanks.

**Comment by blegat** [comment]
Hi, support for noncommutative variables in PolyJuMP and this package would be nice to have indeed. I don't think that this requires a huge work. Thanks a lot for you interest !

**Comment by peterwittek** [comment]
That is awesome, thanks!
